# This is a basic workflow to help you get started with Actions

name: cordova-plugin-chordino
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - run: sed -i -E "s/\"version\"[:]\s*\"[0-9.]+\",/\"version\":\"${GITHUB_REF_NAME#v}\",/g" package.json
      - run: sed -i -E "s/version=\"[0-9.]+\">/version=\"${GITHUB_REF_NAME#v}\">/g" plugin.xml
      - run: yarn
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
